---
app_user: "ubuntu"
http_ip: "0.0.0.0"
http_url: "todoapp.nl"
http_conf: "todoApp.conf"
http_path: "FLASKAPPS"
http_host: "todoApp"
port_5000: "5000"
http_port: "80"
venv: "tdApp"
disable_default: true